# Generated by Django 4.2.7 on 2023-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comments_like",
            field=models.ManyToManyField(
                blank=True, related_name="Comment_Likes", to="authentication.user"
            ),
        ),
    ]
