# Generated by Django 4.2.7 on 2023-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_comment_comments_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.JSONField(default={}),
        ),
    ]
