# Generated by Django 4.2 on 2023-11-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_comment_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_token",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reply",
            field=models.JSONField(default=dict),
        ),
    ]
