# Generated by Django 4.2.7 on 2023-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_secret", models.CharField(max_length=255)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
    ]
